"""initial models

Revision ID: 940a3a9c7df4
Revises: 
Create Date: 2026-09-25 16:07:36.898706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940a3a9c7df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=30), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_type', sa.String(length=30), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('planning_unit_id', sa.Integer(), nullable=True),
    sa.Column('all_skills', sa.Text(), nullable=True),
    sa.Column('skill_start', sa.Date(), nullable=True),
    sa.Column('skill_end', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_unit_id'], ['planning_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)

    op.create_table('forecast_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('offered', sa.Float(), nullable=True),
    sa.Column('aht', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_unit_id'], ['planning_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_intervals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_intervals_planning_unit_id'), ['planning_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_intervals_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_forecast_unit_ts', ['planning_unit_id', 'timestamp'], unique=False)

    op.create_table('requirement_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agents_required', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_unit_id'], ['planning_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_intervals', schema=None) as batch_op:
        batch_op.create_index('ix_req_unit_ts', ['planning_unit_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_intervals_planning_unit_id'), ['planning_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_intervals_timestamp'), ['timestamp'], unique=False)

    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('mon', sa.String(length=10), nullable=True),
    sa.Column('tue', sa.String(length=10), nullable=True),
    sa.Column('wed', sa.String(length=10), nullable=True),
    sa.Column('thu', sa.String(length=10), nullable=True),
    sa.Column('fri', sa.String(length=10), nullable=True),
    sa.Column('sat', sa.String(length=10), nullable=True),
    sa.Column('sun', sa.String(length=10), nullable=True),
    sa.Column('shift_start', sa.String(length=10), nullable=True),
    sa.Column('shift_end', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodations_employee_id'), ['employee_id'], unique=False)

    op.create_table('pto_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('pto_type', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pto_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pto_entries_employee_id'), ['employee_id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('planning_unit_id', sa.Integer(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['planning_unit_id'], ['planning_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_sched_date_unit', ['schedule_date', 'planning_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_employee_id'))
        batch_op.drop_index('ix_sched_date_unit')

    op.drop_table('schedules')
    with op.batch_alter_table('pto_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pto_entries_employee_id'))

    op.drop_table('pto_entries')
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodations_employee_id'))

    op.drop_table('accommodations')
    with op.batch_alter_table('requirement_intervals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_intervals_timestamp'))
        batch_op.drop_index(batch_op.f('ix_requirement_intervals_planning_unit_id'))
        batch_op.drop_index('ix_req_unit_ts')

    op.drop_table('requirement_intervals')
    with op.batch_alter_table('forecast_intervals', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_unit_ts')
        batch_op.drop_index(batch_op.f('ix_forecast_intervals_timestamp'))
        batch_op.drop_index(batch_op.f('ix_forecast_intervals_planning_unit_id'))

    op.drop_table('forecast_intervals')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))

    op.drop_table('employees')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('planning_units')
    op.drop_table('data_uploads')
    op.drop_table('api_connections')
    # ### end Alembic commands ###
